#!/usr/bin/env Rscript

###### 
# This script will summarize the age and sex association files from gemma, calculating
# q-values for the lrt p-value. It will print a summary table of significant results
# by q-value cutoff and print example plots of significant associations.  
# input: 	association files from sex and age
#			bacterial data
#			covariate file
# output: 	histogram/qqplot file for sex and age
#			tables that list q-values for the lrt pvalue for sex and age
#			summary table of significant bacteria by q-value cutoff
#			example plots for associations for sex and age that are significant
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


##### Read in arguments from command line:
args <- commandArgs(trailingOnly=TRUE)
prefix <- args[1] # name of season etc 
cluster.in <- args[2] # path to where the files are stored
output.path <- args[3] # path to the where we want the files written to
taxa.file <- args[4] # path and name of the bacterial abundance information
cov.file <- args[5] # path and name of the covariate information
plotcol <- args[6] # color to plot points



##### Load libraries:
library(qvalue)

##### Load in p-value, bacterial, and covariate data:
print("loading in association and bacterial data")
taxa <- read.table(file=taxa.file, sep="\t", header=TRUE)
covs <- read.table(file=cov.file, sep="\t", header=TRUE)

age.files <- list.files(cluster.in, pattern="out.age.")
sex.files <- list.files(cluster.in, pattern="out.sex.")

age.assoc.files <- age.files[grep("assoc", age.files)]
age.log.files <- age.files[grep("log", age.files)]
sex.assoc.files <- sex.files[grep("assoc", sex.files)]
sex.log.files <- sex.files[grep("log", sex.files)]



##### Make table of the p-values, pve, and se(pve):
print("generating tables of p-values, pve, and se(pve)")
age.pvals <- c()
for (i in 1:length(age.assoc.files)) {
	bacteria <- gsub("out.age.covs.regressed.", "", gsub(paste(".",prefix,".*.assoc.txt", sep=""),"", age.assoc.files[i]))
	pvals <- read.table(file=paste(cluster.in,age.assoc.files[i], sep=""), header=TRUE, sep="\t")
	
	log <- read.table(file=paste(cluster.in, age.log.files[grep(bacteria, age.log.files)], sep=""), sep="\n", header=FALSE, comment.char="?", stringsAsFactors=FALSE)$V1
	pveline <- grep("pve estimate", log)
	PVE <- gsub("## pve estimate in the null model = ", "", log[pveline])
	sePVE <- gsub("## se\\(pve\\) in the null model = ", "", log[pveline+1])
	
	pval <- c(bacteria, as.numeric(pvals[8:length(pvals)]), PVE, sePVE)
	age.pvals <- rbind(age.pvals, pval)
}
age.qvals <- qvalue(as.numeric(age.pvals[,7]))$qvalue
age.pvals <- cbind(age.pvals, age.qvals)
colnames(age.pvals) <- c("bacteria", "beta", "se", "l_remle", "l_mle", "p_wald", "p_lrt", "p_score", "pve", "se_pve", "lrt_qvalue")
age.pvals <- data.frame(age.pvals, row.names=NULL, stringsAsFactors=FALSE)
write.table(age.pvals, paste(output.path,"table.GEMMA.age.pvalues.", today,"ERD.txt", sep=""), row.names=FALSE, quote=FALSE)



sex.pvals <- c()
for (i in 1:length(sex.assoc.files)) {
	bacteria <- gsub("out.sex.covs.regressed.", "", gsub(paste(".", prefix,".*.assoc.txt", sep=""), "", sex.assoc.files[i]))
	pvals <- read.table(file=paste(cluster.in,sex.assoc.files[i], sep=""), header=TRUE, sep="\t")
	
	log <- read.table(file=paste(cluster.in, sex.log.files[grep(bacteria, sex.log.files)], sep=""), sep="\n", header=FALSE, comment.char="?", stringsAsFactors=FALSE)$V1
	pveline <- grep("pve estimate", log)
	PVE <- gsub("## pve estimate in the null model = ", "", log[pveline])
	sePVE <- gsub("## se\\(pve\\) in the null model = ", "", log[pveline+1])
	
	pval <- c(bacteria, as.numeric(pvals[8:length(pvals)]), PVE, sePVE)
	sex.pvals <- rbind(sex.pvals, pval)
}
sex.qvals <- qvalue(as.numeric(sex.pvals[,7]))$qvalue
sex.pvals <- cbind(sex.pvals, sex.qvals)
colnames(sex.pvals) <- c("bacteria", "beta", "se", "l_remle", "l_mle", "p_wald", "p_lrt", "p_score", "pve", "se_pve", "lrt_qvalue")
sex.pvals <- data.frame(sex.pvals, row.names=NULL, stringsAsFactors=FALSE)
write.table(sex.pvals, paste(output.path,"table.GEMMA.sex.pvalues.", today,"ERD.txt", sep=""), row.names=FALSE, quote=FALSE)




##### P-value histograms and qqplots for age and sex associations:
print("saving qqplots and histograms of sex and age associations")
# age:
pdf(paste(output.path,"plot.hist.and.qq.plot.age.assns.",prefix,".gemma.",today,"ERD.pdf", sep=""), width=10, height=5)
par(mfrow=c(1,2))
hist(as.numeric(as.character(age.pvals$p_lrt)), col=plotcol, breaks=20, xlab="p-value", main="Distribution of LMM LRT p-values: age")

o <- -log10(sort(as.numeric(as.character(age.pvals$p_lrt)), decreasing=F))
e <- -log10(1:length(o)/length(o))
plot(e,o, main=paste("QQplot for age\n",prefix," - LMM LRT", sep=""), pch=16, col=rgb(0,0,0,alpha=0.5), xlab="expected", ylab="observed")
abline(0,1, col="red")
dev.off()

# sex:
pdf(paste(output.path,"plot.hist.and.qq.plot.sex.assns.", prefix,"gemma.",today,"ERD.pdf", sep=""), width=10, height=5)
par(mfrow=c(1,2))
hist(as.numeric(as.character(sex.pvals$p_lrt)), col=plotcol, breaks=20, xlab="p-value", main="Distribution of LMM LRT p-values: sex")

o <- -log10(sort(as.numeric(as.character(sex.pvals$p_lrt)), decreasing=F))
e <- -log10(1:length(o)/length(o))
plot(e,o, main=paste("QQplot for sex\n",prefix," - LMM LRT", sep=""), pch=16, col=rgb(0,0,0,alpha=0.5), xlab="expected", ylab="observed")
abline(0,1, col="red")
dev.off()




##### Save summary tables of significant bacteria at different q-value cutoffs:
print("saving summary tables of significant q values at various cutoffs")
qvals <- c(0.001, 0.01, 0.05, 0.10, 0.2, 1)
qval.summary <- matrix(NA, ncol=2, nrow=length(qvals))
howmany <- function(x, cutoff) {
	length(which(x <= cutoff))
}
for (i in 1:length(qvals)) {
	qval.summary[i,1] <- howmany(as.numeric(as.character(age.pvals$lrt_qvalue)), qvals[i])
	qval.summary[i,2] <- howmany(as.numeric(as.character(sex.pvals$lrt_qvalue)), qvals[i])
}

rownames(qval.summary) <- qvals
colnames(qval.summary) <- c("age", "sex")
write.table(qval.summary, paste(output.path, "table.summary.q.values.at.various.cutoffs.age.sex.",today,"ERD.txt", sep=""), sep="\t", quote=FALSE)



##### Plot associations for significant results:
print("plotting examples of significant results")
# age:
for (i in 1:dim(age.pvals)[1]) {
	if (as.numeric(as.character(age.pvals$lrt_qvalue[i])) <= 0.1) {
		bacteria <- age.pvals$bacteria[i]
		pdf(paste(output.path, "plot.age.",age.pvals$bacteria[i],".association.gemma.",today,"ERD.pdf", sep=""))
		lm.out <- lm(as.numeric(taxa[grep(bacteria, rownames(taxa)),]) ~ covs$Age.)
		plot(covs$Age., as.numeric(taxa[grep(bacteria, rownames(taxa)),]), xlab="age (years)", ylab="normalized abundance", pch=16, col=plotcol, main=paste(age.pvals$bacteria[i]," by age - PVE = ",as.numeric(as.character(age.pvals$pve[i]))*100,"\np-value = ",as.numeric(as.character(age.pvals$p_lrt[i], 5))," q-value = ",as.numeric(as.character(age.pvals$lrt_qvalue[i], 4)), sep=""))
		abline(a=lm.out$coefficients[1], b=lm.out$coefficients[2], col="gray")
		dev.off()
	}
}

for (i in 1:dim(sex.pvals)[1]) {
	if (as.numeric(as.character(sex.pvals$lrt_qvalue[i])) <= 0.05) {
		bacteria <- sex.pvals$bacteria[i]
		pdf(paste(output.path,"plot.sex.",sex.pvals$bacteria[i],".association.gemma.",today,"ERD.pdf", sep=""))
		stripchart(as.numeric(taxa[grep(bacteria, rownames(taxa)),]) ~ covs$Sex., vertical=TRUE, xlab="sex", method="jitter", ylab="normalized abundance", pch=16, col=plotcol, main=paste(sex.pvals$bacteria[i]," by sex - PVE = ", as.numeric(as.character(age.pvals$pve[i]))*100,"\np-value = ",round(as.numeric(as.character(sex.pvals$p_lrt[i])), 4)," q-value = ",round(as.numeric(as.character(sex.pvals$lrt_qvalue[i])), 5), sep=""))
		boxplot(as.numeric(taxa[grep(bacteria, rownames(taxa)),]) ~ covs$Sex., add=TRUE, boxwex=0.35, names=c(" ", " "), notch=TRUE, outline=FALSE) 
		dev.off()
	}
}

print("DONE!")