#!/usr/bin/env Rscript

###### 
# This script will compile all of the results of the heritability estimates run using
# Mark's heritiability program. 
# To run from command line:
# 1. path to the heritability files
# 2. the end of the name of the heritability files
# 3. the folder you want the files this script generates to be written to
# 4. the color you want the points to be on the figure
# input:		output files from running the heritabilities.py script
# output: 		table of the top model with p-value for all bacteria
#				table of the all models with p-values for all bacteria
#				table of addenv model p-values
#				plots of the correlation between summer and winter for h2 and H2 
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Read in command line arguments:
args <- commandArgs(trailingOnly=TRUE)
herit.files <- args[1] # path to the folder containing all of the heritability files
suffix <- args[2] # end of the name of the herit files 
out.path <- args[3] # folder you want all of the output files written to
mycol <- args[4] # color you want for plot



###### Get the list of all bacteria that were analyzed for heritability:
print("reading in all GTAM analysis files")
all.files<-list.files(path=herit.files)

all.herit <- c()
for (i in 1:length(all.files)) {
	outputs <- read.table(file=paste(herit.files,all.files[i],"/Outputs/Outputs.summary", sep=""), sep="\t", header=TRUE)
	all.herit <- rbind(all.herit, cbind(rep(all.files[i], dim(outputs)[1]), outputs))
}




##### Generate table of all p-values:
# remove date and initials from bacteria name:
all.herit[,1] <- gsub(suffix, "", all.herit[,1])

colnames(all.herit)[1] <- "bacteria"

# Save table of all model results:
write.table(all.herit, paste(out.path, "heritability_tests_marks_program_",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)

# Save table of only the additive model results:
addenv <- all.herit[which(all.herit$NO. == 2), ]
write.table(addenv, paste(out.path, "heritability_tests_marks_program_addenv_", today, "ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)

h2 <- c()
e <- c()
for (i in 1:dim(addenv)[1]) {
	h2 <- c(h2,strsplit(as.character(addenv$h2[i]), " ")[[1]][1])
	e <- c(e,gsub("\\(", "", gsub("\\)", "", strsplit(as.character(addenv$h2[i]), " ")[[1]][2])))
}

addenv2 <- cbind(addenv[1], addenv$P.value, h2, e)
colnames(addenv2)[2] <- "pvalue"
addenv2[,3] <- as.numeric(as.character(addenv2[,3]))
addenv2[,4] <- as.numeric(as.character(addenv2[,4]))

pdf(paste(out.path, "plot.h2.by.pvalue.with.standard.error.",today,"ERD.pdf", sep=""))
plot(addenv2$pvalue, addenv2$h2, pch=16, col=mycol, ylim=c(0,0.8), xlab="p-value", ylab="h2", main=" narrow-sense heritability estimates with standard errors")
arrows(addenv2$pvalue, addenv2$h2, y1=addenv2$h2-addenv2$e, length=0, col="gray")
arrows(addenv2$pvalue, addenv2$h2, y1=addenv2$h2+addenv2$e, length=0, col="gray")
dev.off()


##### Generate the table of the top model for each bacteria:
print("finding top model for each bacteria")
# Get the list of all bacteria analyzed for heritability:
all.files<-list.files(path=herit.files)

all.herit.best <- c()
for (i in 1:length(all.files)) {
	outputs <- read.table(file=paste(herit.files,all.files[i],"/Outputs/Outputs.summary.sorted", sep=""), sep="\t", header=FALSE)
	if (outputs[1,1] == "NO.") {
		all.herit.best <- rbind(all.herit.best, cbind(all.files[i], outputs[2,]))
	} else {
		all.herit.best <- rbind(all.herit.best, cbind(all.files[i], outputs[1,]))
	}
}

all.herit.best[,1] <- gsub(suffix, "", all.herit.best[,1])

colnames(all.herit.best) <- c("bacteria", as.character(unlist(outputs[1,])))

# Save table of all model results:
print("saving tables of all p-values, top model p-value for each bacteria, and the number of significant top models")
write.table(all.herit.best, paste(out.path, "heritability_tests_marks_program_most_likely_fit_", today, "ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)

# Save table of number of models by category:
write.table(table(all.herit.best$Model), paste(out.path, "table.best.fit.by.model.choice.",today, "ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)


print("DONE!")

