#!/usr/bin/env Rscript

###### 
# This script generate a table of PVE w/se for the bacterial GWAS along with a plot of PVE with standard error 
# input: 		association log files			
# output: 		table of PVEs
#				plot of PVEs with SE
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


##### Read in command line arguments:
args <- commandArgs(trailingOnly=TRUE)
file.path <- args[1] # path to all of the log files
out.path <- args[2] # path where you want the table of PVEs and plot to be written to
plotcol <- args[3] # color you want the points to be on the plot
prefix <- args[4] # prefix of the .log files (before the bacteria name)


##### Read list of all bacteria log files:
print("read in bacteria log files")
files <- list.files(path=file.path, pattern=".log.txt")




##### Read in all PVEs and sd(PVE):
print("read in PVEs")
all.pves <- c()
for (i in 1:length(files)) {
	log <- read.table(file=paste(file.path, files[i], sep=""), sep="\t", comment.char="?", stringsAsFactors=FALSE)$V1
	pve <- gsub("## pve estimate in the null model = ", "", log[grep("pve estimate", log)])
	sdpve <- strsplit(log[grep("pve estimate", log)+1], split = " ")[[1]][8]
	bacteria <- gsub(prefix, "", gsub(".column.*.log.txt", "", files[i]))
	all.pves <- rbind(all.pves, c(bacteria, pve, sdpve))
}	

sig <- c()



##### Do any of the bacteria display chip heritability:
print("checking if any are heritable")
for (i in 1:dim(all.pves)[1]) {
	if (all.pves[i,3] == "nan" ) {
		sig <- c(sig, "x")
	} else if (as.numeric(all.pves[i,2]) > as.numeric(all.pves[i,3])) {
		sig <- c(sig, "heritable")
	} else {
		sig <- c(sig, "x")
	}
}

tozero <- (as.numeric(all.pves[,2])-as.numeric(all.pves[,3]))
tozero[is.na(tozero)] <- -1000

ordered.sig <- all.pves[order(tozero, decreasing=TRUE),]
ordered.sig[which(ordered.sig == "nan")] <- 0


##### Plot chip heritability with standard error:
print("plotting PVE with SE")
pdf(paste(out.path, "plot.PVE.by.bacteria.with.standard.error.",today,"ERD.pdf", sep=""))
plot(1:dim(ordered.sig)[1], ordered.sig[,2], pch=16, col=plotcol, ylim=c(0,1), xlab="bacteria", ylab="PVE", main="PVE with standard errors")
arrows(x0 = 1:dim(ordered.sig)[1], y0 = as.numeric(ordered.sig[,2]), y1 = (as.numeric(ordered.sig[,2])-as.numeric(ordered.sig[,3])), length=0, col="gray")
arrows(x0 = 1:dim(ordered.sig)[1], y0 = as.numeric(ordered.sig[,2]), y1 = (as.numeric(ordered.sig[,2])+as.numeric(ordered.sig[,3])), length=0, col="gray")
dev.off()



##### Saving PVE table:
print("saving table of PVE by bacteria")
colnames(all.pves) <- c("bacteria", "PVE", "se(PVE)")
write.table(all.pves, paste(out.path, "table.PVE.by.bacteria.",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)

print("DONE!")
 