#!/usr/bin/env Rscript

###### 
# This script will generate tables to run a linear mixed model for associations of bacteria 
# to age and sex using Gemma with the bacteria as the response variable and age or sex
# as the independent variable. The other covariates are regressed out before running 
# GEMMA. 
# This script can be run on command line with the following arguments specified:
# 1. Season (or other prefix)
# 2. name and location of the bacterial data file
# 3. name and location of the covariate file
# 4. name and location of the relatedness matrix on the cluster
# 5. name and location of script you want to write to start running GEMMA
# input: 	bacteria data file
#			covariates of interest
# output: 	mean genotype file for gemma
#			phenotype file for gemma
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#output.path <- c("/Users/erdavenport/Dropbox/Lab/Poop/Sequencing_Results/39_FC1to4_seasons_individually/")	# path for all output to go into
#cluster.out <- c("/Users/erdavenport/clusterhome/Programs/Gemma/sex_age_phenos_seasons_individually_covs_regressed_out_052014/")
#cluster.script <- c("/mnt/lustre/home/erdavenport/Programs/Gemma/sex_age_phenos_seasons_individually_covs_regressed_out_052014/")
#subfolder <- c("2_Gemma_for_sex_and_age_051914/")		# Optional folder for putting initial data files into
##subfolder2 <- c("1_covs_regressed_out_051914/")
#############################


##### Read in arguments from the command line:
args <- commandArgs(trailingOnly=TRUE)
prefix <- args[1] # season
bacterial.data <- args[2] # bacterial taxa file
covariate.data <- args[3] # covariate file
relatedness.matrix <- args[4] # location and name of relatedness matrix
cluster.out <- args[5] # folder on the cluster you want to write all the files out to
cluster.script <- args[6] # path to folder containing files on the cluster

print(paste("prefix:", prefix))
print(paste("bacterial data file:", bacterial.data))
print(paste("covariate data file:", covariate.data))
print(paste("relatedness matrix:", relatedness.matrix))
print(paste("path to write files to on the cluster:", cluster.out))
print(paste("path to files on the cluster:", cluster.script))


##### Load in bacterial data:
data <- read.table(file=bacterial.data, sep="\t", header=TRUE)



##### Load in covariate data:
# create "genotype" file (age and sex):
print("generating 'genotype' file")

covs <- read.table(file=covariate.data, sep="\t", header=TRUE)
sex <- as.numeric(covs$Sex.) - 1 # female is 0, male is 1




##### Save "genotype" files:
age.geno <- t(data.frame(c("age", rep(NA, 2), covs$Age.)))
sex.geno <- t(data.frame(c("sex", rep(NA, 2), sex)))

write.table(age.geno, paste(cluster.out,"genotype.file.age.covs.regressed.", prefix,".",today,"ERD.txt", sep=""), sep="\t", col.names=FALSE, row.names=FALSE, quote=FALSE)
write.table(sex.geno, paste(cluster.out, "genotype.file.sex.covs.regressed.", prefix,".", today,"ERD.txt", sep=""), sep="\t", col.names=FALSE, row.names=FALSE, quote=FALSE)



##### Regressing out col/age from bacteria for sex phenotype:
# Regressing out age and colony all at the same time:
print("Generating sex data...")
sexdata <- c()
myrownames <- c()
for (i in 1:dim(data)[1]) {
	mylm <- lm(as.numeric(data[i,]) ~ as.numeric(covs$Age.) + as.factor(covs$colony), na.action=na.exclude)
	resids <- resid(mylm)
	sexdata <- rbind(sexdata, resids)
}
colnames(sexdata) <- gsub("X", "", colnames(data))
myrownames <- c(myrownames, rownames(data))
rownames(sexdata) <- myrownames



##### Regressing out col/sex from bacteria for age phenotype:
# Regressing out sex and colony all at the same time:
print("Generating age data...")
agedata <- c()
myrownames <- c()
for (i in 1:dim(data)[1]) {
	mylm <- lm(as.numeric(data[i,]) ~ as.factor(covs$Sex.) + as.factor(covs$colony), na.action=na.exclude)
	resids <- resid(mylm)
	agedata <- rbind(agedata, resids)
}
colnames(agedata) <- gsub("X", "", colnames(data))
myrownames <- c(myrownames, rownames(data))
rownames(agedata) <- myrownames



##### Generating phenotype files and run script:
print("generating 'phenotype' files and run script") 
script <- c("#!/bin/bash")
for (i in 1:dim(data)[1]) {
	# Generate phenotype files:
	age.pheno.file <- paste("phenotype.file.age.covs.regressed.",rownames(data)[i],".", prefix,".", today,"ERD.txt", sep="")
	sex.pheno.file <- paste("phenotype.file.sex.covs.regressed.",rownames(data)[i],".", prefix,".", today,"ERD.txt", sep="")
	
	write.table(agedata[i,], paste(cluster.out, age.pheno.file , sep=""), sep="\n", col.names=FALSE, row.names=FALSE, quote=FALSE)
	write.table(sexdata[i,], paste(cluster.out, sex.pheno.file , sep=""), sep="\n", col.names=FALSE, row.names=FALSE, quote=FALSE)

	# Add to script:
	script <- c(script, paste("qsub -l h_vmem=2g,bigio=4 ~/repos/scripts_repo/poop_scripts/submit_GEMMA_age_sex_041314ERD.sh ",cluster.script,"genotype.file.age.covs.regressed.", prefix,".",today,"ERD.txt ",cluster.script,age.pheno.file," ",relatedness.matrix," out.age.covs.regressed.",rownames(data)[i],".", prefix,".", today,"ERD", sep=""))
	script <- c(script, paste("qsub -l h_vmem=2g,bigio=4 ~/repos/scripts_repo/poop_scripts/submit_GEMMA_age_sex_041314ERD.sh ",cluster.script,"genotype.file.sex.covs.regressed.", prefix,".",today,"ERD.txt ",cluster.script,sex.pheno.file," ",relatedness.matrix," out.sex.covs.regressed.",rownames(data)[i],".", prefix,".", today,"ERD", sep=""))
}

write.table(script, paste(cluster.out, "run_gemma_sex_and_age_assns_",prefix,"_covs_",today,"ERD.sh", sep=""), sep="\n", quote=FALSE, row.names=FALSE, col.names=FALSE)

print("DONE!")
	
	
