#!/usr/bin/env Rscript

###### 
# This script outputs 1. a .fam file where every column contains a different bacteria and
# 2. a script to run GEMMA using that .fam file on the cluster.
# input: 	data table of qqnormed combined bacteria
#			covariate file (sex and age of individuals)
#			colony file
# output: 	script to run GEMMA on all bacteria on the cluster
#			.fam file 
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Take in command line arguments:
args <- commandArgs(trailingOnly=TRUE)
bacteria.data.file <- args[1] # path and name of the bacterial data file to use
covariates <- args[2] # path and name of the covariate file to use
fam.file <- args[3] # path and name of the fam file to use
famname <- args[4] # the prefix to use for the association files
cluster.out <- args[5] # path to write the files out to on the cluster
output.path <- args[6] # path to write files out to on dropbox
script.name <- args[7] # name of the submit script for the cluster (no date or .sh)

print(paste("bacterial data file:", bacteria.data.file))
print(paste("covariate file:", covariates))
print(paste(".fam file:", fam.file))
print(paste("file prefix:", famname))
print(paste("path on cluster to write out to:", cluster.out))
print(paste("path on dropbox to write out to:", output.path))


##### Load in data:
print("Loading data...")
log.QTL.data <- read.table(file=bacteria.data.file, sep="\t", header=TRUE)
my.covs <- read.table(file=covariates, sep="\t", header=TRUE)
fam <- read.table(file=fam.file, sep=" ", header=FALSE)



##### Regress out age, sex, and colony from bacteria:
print("Regressing out covariates...")
newdata <- c()
myrownames <- c()
for (i in 1:dim(log.QTL.data)[1]) {
	mylm <- lm(as.numeric(log.QTL.data[i,]) ~ as.numeric(my.covs$Age.) + as.factor(my.covs$Sex.) + as.factor(my.covs$colony), na.action=na.exclude)
	resids <- resid(mylm)
	newdata <- rbind(newdata, resids)
}
colnames(newdata) <- gsub("X", "", colnames(log.QTL.data))
myrownames <- c(myrownames, rownames(log.QTL.data))
rownames(newdata) <- myrownames
log.QTL.data <- newdata


##### Add bacteria to fam file:
print("Generating .fam file...")
# Add extra columns to fam file for the number of traits (-1) being analyzed:
xtra <- matrix(c(-9), nrow=dim(fam)[1], ncol=(dim(log.QTL.data)[1]-1))
fam2 <- data.frame(fam, xtra)

# Add data into the fam file:
for (j in 1:dim(log.QTL.data)[2]) {
	fam2[which(fam2[,2] == gsub("FC1to4_poop_", "", colnames(log.QTL.data)[j])), 6:dim(fam2)[2]] <- log.QTL.data[,j]
}

colnames(fam2) <- c("HUTTERITES", "FINDIV", "DAD", "MOM", "SEX", rownames(log.QTL.data))

write.table(fam2, paste(cluster.out,famname,today,"ERD.fam", sep=""), sep=" ", row.names=FALSE, col.names=FALSE, quote=FALSE)
write.table(fam2, paste(output.path,famname,"with.labs.",today,"ERD.fam", sep=""), sep=" ", row.names=FALSE, quote=FALSE)


	
##### Write a shell script to run on the cluster:
print("Writing shell script...")	
script <- c("#!/bin/bash")
script <- c(script, paste("cp /mnt/lustre/home/erdavenport/Programs/Gemma/hutt.3chip.hg19remap.bim /mnt/lustre/home/erdavenport/Programs/Gemma/",famname,today,"ERD.bim", sep=""))
script <- c(script, paste("cp /mnt/lustre/home/erdavenport/Programs/Gemma/hutt.3chip.hg19remap.bed /mnt/lustre/home/erdavenport/Programs/Gemma/",famname,today,"ERD.bed", sep=""))
for (i in 1:dim(log.QTL.data)[1]) {
	script <- c(script, paste("qsub -l h_vmem=2g,bigio=1 ~/repos/scripts_repo/poop_scripts/run_GEMMA_poopQTL_032414ERD.sh ",famname,today,"ERD ",famname,rownames(log.QTL.data)[i],".column.",i,".out.",today,"ERD ",i, sep=""))
}
write.table(script, paste(cluster.out, script.name,"_",today,"ERD.sh", sep=""), sep="\n", quote=FALSE, row.names=FALSE, col.names=FALSE)



print("DONE!")


