#!/usr/bin/env Rscript

###### 
# This script will calculate the enrichment of p-values overlapping DHS sites in the 53 
# DHS samples from Duke Encode and the 349 from the Maurano study. It will output a table 
# of these enrichments at various cutoffs for further analysis. In addition, it will calculate
# a Fisher's Exact test p-value and save that to a table.
#
# Usage:
# ./maurano_enrichment_script_with_FET_062614ERD.R <path.to.GWAS> <bed.file> <out.path> <enr.subfolder> <pval.subfolder> <prefix>
# 1. path.to.GWAS: path to all assoc files
# 2. bed.file: bed file of intersection of Maurano SNPs and Hutterite SNPs
# 3. out.path: path to where you want to save all enrichment tables and p-value tables
# 4. enr.subfolder: name of the folder to save the enrichments file to (in out.path)
# 5. pval.subfolder: name of the folder to save the p-value file to (in out.path)
# 6. prefix: the prefix of the assoc file name
#
# input: 		assoc files from GWAS	
#				Maurano/Hutterite intersect bed file
# output: 		tables of enrichment at various cutoffs for GWAS p-values for each bacteria
#				bed file with only the SNPs included in this analysis with these samples
#				tables of FET p-values for each bacteria
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


##### Read in command line arguments;
args <- commandArgs(trailingOnly=TRUE)
path.to.GWAS <- args[1] # path to all of the GWAS files to be analyzed
bed.file <- args[2] # path to the bed file containing all Maurano DHS peaks
out.path <- args[3] # base folder to write out all files
enr.subfolder <- args[4] # subfolder to write the enrichment files to 
pval.subfolder <- args[5] # subfolder to write FET pvalues to
prefix <- args[6] # prefix of GWAS files



##### Create lists of all GWAS files:
print("getting list of GWAS")
GWAS <- list.files(path=path.to.GWAS, pattern=".assoc.")



##### Load in summary of bed intersection files and coding information:
print("getting list of DHS intersections")
BEDS <- read.table(file=bed.file, sep="\t", header=TRUE)


##### Prune SNPS in BED and coding.annos by what was actually in the study:
gwa <- read.table(file=paste(path.to.GWAS,GWAS[1], sep=""), sep="\t", colClasses=c("numeric", "character", "numeric", "numeric", "character", "character", "numeric", "numeric", "numeric"), header=TRUE)
beds <- BEDS[which(as.character(BEDS$rs) %in% as.character(gwa$rs)),]
write.table(beds, paste(out.path,"table.349.Maurano.DHS.overlaps.with.Hutt.SNPS.",today,"ERD.txt", sep=""), row.names=FALSE, quote=FALSE, sep="\t")


##### Calculate the baseline number of noncoding SNPs that overlap DHSs in the study:
print("calculating baseline overlaps")
baseline <- c()
for (i in 5:dim(beds)[2]) {
	baseline <- c(baseline, length(which(beds[,i] == 1))/dim(beds)[1])
}

thresholds <- c(1.0, 0.5, 0.1, 0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001, 0.00005, 0.00001, 0.000005, 0.000001, 0.0000005, 0.0000001, 0.00000005, 0.00000001)



##### Calculate enrichments for each bacteria in each cell type:
for (i in 1:length(GWAS)) {
	print(paste("enrichment for ",i," of ", length(GWAS), sep=""))
	gwa <- read.table(file=paste(path.to.GWAS,GWAS[i], sep=""), sep="\t", colClasses=c("numeric", "character", "numeric", "numeric", "character", "character", "numeric", "numeric", "numeric"), header=TRUE)
	bacteria <- gsub(prefix, "", gsub(".column.*.assoc.txt", "", GWAS[i]))
	
	# Only want to look at cutoffs where we have some power to say something. Must have at least
	# 50 counts in each bin.
	
	numbers <- c()
	for (j in 1:length(thresholds)) {
		numbers <- c(numbers, length(which(gwa$p_lrt < thresholds[j])))
	}
	
	new.thresholds <- thresholds[which(numbers >= 50)]
	
	# Calculate enrichments:
	enrichments <- matrix(NA, nrow=dim(beds)[2]-4, ncol=length(new.thresholds))
	for (j in 5:dim(beds)[2]) {
		for (k in 1:length(new.thresholds)) {
			#		A									B													C								D									
			# A = enrichment
			# B = the number of SNPs under the given threshold that overlap DHS sites in that tissue
			# C = the number of SNPs under the given threshold in the GWAS
			# D = the number of SNPs under DHS sites in that tissue
			enrichments[j-4,k] <- length(which(gwa$p_lrt < new.thresholds[k] & beds[,j] == 1))/length(which(gwa$p_lrt < new.thresholds[k]))/baseline[j-4]
		}
	}
	
	colnames(enrichments) <- new.thresholds
	rownames(enrichments) <- colnames(beds)[5:dim(beds)[2]]
	
	write.table(enrichments, paste(out.path, enr.subfolder, "table.Maurano.enrichments.",bacteria,".",today,"ERD.txt", sep=""), sep="\t", quote=FALSE)

	# Calculate FET p-value:
	pvals <- matrix(NA, nrow=dim(beds)[2]-4, ncol=length(new.thresholds))
	for (j in 5:dim(beds)[2]) {
		for (k in 1:length(new.thresholds)) {
			os <- length(which(gwa$p_lrt < new.thresholds[k] & beds[,j] == 1))
			on <- length(which(gwa$p_lrt >= new.thresholds[k] & beds[,j] == 1))
			ns <- length(which(gwa$p_lrt < new.thresholds[k] & beds[,j] == 0))
			nn <- length(which(gwa$p_lrt >= new.thresholds[k] & beds[,j] == 0))
		
			ctable <- matrix(c(os, on, ns, nn), nrow=2, ncol=2, byrow=TRUE)
			pvals[j-4,k] <- fisher.test(ctable, alternative = "greater")$p.value
		}
	}
	
	colnames(pvals) <- new.thresholds
	rownames(pvals) <- colnames(beds)[5:dim(beds)[2]]
	
	write.table(pvals, paste(out.path, pval.subfolder, "table.Maurano.enrichment.pvalues.",bacteria,".",today,"ERD.txt", sep=""), sep="\t", quote=FALSE)
}

print("DONE!")
	
	
