#!/usr/bin/env Rscript

###### 
# This script creates all of the files that are to be used in calculating heritability
# using Mark's program. 
# input:		summer and winter bacterial information
#				covariates for all of the Hutterite individuals used in the study
# output: 		ph-cvt files for each bacteria
#				phenolist to run GTAM
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
output.path <- c("/Users/erdavenport/Dropbox/Lab/Poop/Sequencing_Results/37_FC1to4_seasons_averaged/")	# path for all output to go into
output.folder <- c("4_files_for_GTAM_041514/")	# Path for output
#############################



##### Read in command line arguments:
args <- commandArgs(trailingOnly=TRUE)
bacterial.file <- args[1] # path and name of bacterial taxa file
covariate.file <- args[2] # path and name of covariate file
phcvt.out <- args[3] # path of where to write out phcvt files
phenolist <- args[4] # path and name to write out phenolist
prefix <- args[5]



##### Read in bacteria files:
print("reading in bacterial data")
taxa <- read.table(file=bacterial.file, sep="\t", header=TRUE)




##### Read in covariate file:
print("reading in covariate data")
covs <- read.table(file=covariate.file, sep="\t", header=TRUE)

# Convert sex to binary 0 (female) 1 (male):
covs$Sex. <- as.numeric(covs$Sex.)-1

##### Set up colony covariates:
newelm <- rep(0, dim(covs)[1])
rosedale <- rep(0, dim(covs)[1])
oaklane <- rep(0, dim(covs)[1])
rockport <- rep(0, dim(covs)[1])

for (i in 1:dim(covs)[1]) {
	if (covs$colony[i] == "New Elmspring") {
		newelm[i] <- 1
	} else if (covs$colony[i] == "Rosedale") {
		rosedale[i] <- 1
	} else if (covs$colony[i] == "Oaklane") {
		oaklane[i] <- 1
	} else if (covs$colony[i] == "Rockport") {
		rockport[i] <- 1
	}
}

##### Generate ph-cvt files:
print("generating ph-cvt files")
phenotypes <- c()
for (i in 1:dim(taxa)[1]) {
	phcvt <- cbind(covs[,1], as.numeric(taxa[i,]), rep("1", dim(taxa)[2]), covs[,2], covs[,3], newelm, rosedale, oaklane, rockport) 
	colnames(phcvt) <- c("findiv", paste(rownames(taxa)[i], sep=""), "int", "age", "sex", "colony_newElm", "colony_rosedale", "colony_oaklane", "colony_rockport")
	write.table(phcvt, paste(phcvt.out,rownames(taxa)[i],".",prefix,".",today,"ERD.ph-cvt", sep=""), row.names=FALSE, quote=FALSE, sep="\t")
	phenotypes <- c(phenotypes, paste(rownames(taxa)[i],".",prefix,".",today,"ERD", sep=""))
}


print("saving phenolist file")
write.table(phenotypes, phenolist, sep="\n", quote=FALSE, col.names=FALSE, row.names=FALSE)

print("DONE!")
	










	